# Generated by Django 4.2.16 on 2024-11-30 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_passwordresetotp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='passwordresetotp',
            table='password_reset_otp',
        ),
    ]
